//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadUsuario
    {
        public int IdActividadUsuario { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string TipoActividad { get; set; }
        public Nullable<int> IdCursoSlot { get; set; }
    
        public virtual CursoSlot CursoSlot { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
