//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenidoCurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContenidoCurso()
        {
            this.ContenidoCursoInscripcion = new HashSet<ContenidoCursoInscripcion>();
        }
    
        public int IdContenidoCurso { get; set; }
        public int IdCurso { get; set; }
        public string Archivo { get; set; }
        public string TipoArchivo { get; set; }
        public string Nombre { get; set; }
    
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenidoCursoInscripcion> ContenidoCursoInscripcion { get; set; }
    }
}
