//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoSlot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoSlot()
        {
            this.ActividadUsuario = new HashSet<ActividadUsuario>();
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int IdCursoSlot { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public int IdSlot { get; set; }
        public Nullable<System.DateTime> FechaHoraInicio { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public Nullable<int> Intentos { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Estado { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Horas { get; set; }
        public Nullable<int> Puntos { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public System.DateTime FechaHoraUltimaActualizacion { get; set; }
        public Nullable<int> Orden { get; set; }
        public int Ano { get; set; }
        public Nullable<int> IdCursoSlotDependiente { get; set; }
        public string NombreSlot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadUsuario> ActividadUsuario { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Slot Slot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta> Pregunta { get; set; }
    }
}
