//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoTrabajador
    {
        public int IdGrupoTrabajador { get; set; }
        public int IdTrabajador { get; set; }
        public int IdGrupo { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public Nullable<System.DateTime> FechaHoraDesasignacion { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
