//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscripcion()
        {
            this.Intento = new HashSet<Intento>();
            this.MaterialInscripcion = new HashSet<MaterialInscripcion>();
            this.ContenidoCursoInscripcion = new HashSet<ContenidoCursoInscripcion>();
        }
    
        public int IdInscripcion { get; set; }
        public int IdCursoSlot { get; set; }
        public int IdTrabajador { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public System.DateTime FechaHoraUltimaActualizacion { get; set; }
        public string Certificado { get; set; }
        public Nullable<System.DateTime> FechaHoraAprobacion { get; set; }
        public Nullable<System.DateTime> FechaHoraDescargaCertificado { get; set; }
        public Nullable<double> Puntaje { get; set; }
    
        public virtual CursoSlot CursoSlot { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intento> Intento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInscripcion> MaterialInscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenidoCursoInscripcion> ContenidoCursoInscripcion { get; set; }
    }
}
