//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intento()
        {
            this.Respuesta = new HashSet<Respuesta>();
        }
    
        public int IdIntento { get; set; }
        public int IdInscripcion { get; set; }
        public Nullable<double> NotaMaxima { get; set; }
        public Nullable<double> Puntaje { get; set; }
        public Nullable<double> Nota { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public string Certificado { get; set; }
        public Nullable<System.DateTime> FechaHoraAprobacion { get; set; }
        public Nullable<System.DateTime> FechaHoraRegistro { get; set; }
        public System.DateTime FechaHoraUltimaActualizacion { get; set; }
        public bool Terminado { get; set; }
        public Nullable<System.DateTime> FechaHoraCertificadoDescargado { get; set; }
        public int NumeroIntento { get; set; }
    
        public virtual Inscripcion Inscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuesta { get; set; }
    }
}
