//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInscripcion
    {
        public int IdMaterialInscripcion { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public int IdInscripcion { get; set; }
        public Nullable<bool> Visto { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public string Nombre { get; set; }
        public string TipoMaterial { get; set; }
        public string Archivo { get; set; }
        public Nullable<bool> Obligatorio { get; set; }
    
        public virtual Inscripcion Inscripcion { get; set; }
        public virtual Material Material { get; set; }
    }
}
