//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int IdRespuesta { get; set; }
        public int IdPregunta { get; set; }
        public int IdIntento { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Correcta { get; set; }
    
        public virtual Intento Intento { get; set; }
        public virtual Pregunta Pregunta { get; set; }
        public virtual Pregunta Pregunta1 { get; set; }
    }
}
