//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slot()
        {
            this.CursoSlot = new HashSet<CursoSlot>();
        }
    
        public int IdSlot { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<double> Izquierda { get; set; }
        public Nullable<double> Alto { get; set; }
        public Nullable<double> Ancho { get; set; }
        public string ColorText { get; set; }
        public string ColorBackground { get; set; }
        public string NombreSlot { get; set; }
        public bool CursosDependientes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoSlot> CursoSlot { get; set; }
    }
}
