//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Subordinado = new HashSet<Trabajador>();
            this.Usuario = new HashSet<Usuario>();
            this.GrupoTrabajador = new HashSet<GrupoTrabajador>();
        }
    
        public int IdTrabajador { get; set; }
        public Nullable<int> IdTrabajadorJefe { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Foto { get; set; }
        public string Puesto { get; set; }
        public string Celular { get; set; }
        public string Area { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
        public string Genero { get; set; }
        public bool Eliminado { get; set; }
        public string Provincia { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> IdGrupoOcupacional { get; set; }
        public string DNI { get; set; }
        public string Sede { get; set; }
        public string Codigo { get; set; }
        public string AreaSuperior { get; set; }
        public string Gerencia { get; set; }
        public string Rol { get; set; }
        public string Compañia { get; set; }
    
        public virtual GrupoOcupacional GrupoOcupacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajador> Subordinado { get; set; }
        public virtual Trabajador Jefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoTrabajador> GrupoTrabajador { get; set; }
    }
}
