//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.SOOM.CursosVirtuales.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.ActividadUsuario = new HashSet<ActividadUsuario>();
            this.Personaje = new HashSet<Personaje>();
            this.SuscripcionNotificacion = new HashSet<SuscripcionNotificacion>();
        }
    
        public int IdUsuario { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Eliminado { get; set; }
        public string Perfil { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
        public string PasswordAntiguo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadUsuario> ActividadUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personaje> Personaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuscripcionNotificacion> SuscripcionNotificacion { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
